logging:
  structured:
      file: ecs
server.port: 5000
server:
  forward-headers-strategy: framework
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  kafka:
    producer:
      client-id: user-svc
      bootstrap-servers: kafka-svc:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      auto-index-creation: true
  config:
    import:
      - "optional:dev.yaml"
      - "optional:IT.yaml"
      - "optional:staging.yaml"
  application:
    name: user-svc
springdoc:
  open-api:
    info:
      version: ${APP_VERSION}
      title: User Service management API
      description: Contains endpoints for managing users
      contact:
        name: NgoDat0103
        url: https://github.com/NGODAT0103
        email: 21521935@gm.uit.edu.vn
  api-docs:
    path: /api/v1/users/api-docs
  swagger-ui:
    path: /api/v1/users/ui-docs
    use-root-path: true
  show-actuator: true