server.port: 5000
server:
  forward-headers-strategy: framework
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  data:
    mongodb:
      auto-index-creation: true
  config:
    import:
      - "optional:dev.yaml"
  application:
    name: user-svc
springdoc:
  api-docs:
    path: /api/v1/users/api-docs
  swagger-ui:
    path: /api/v1/users/ui-docs
    use-root-path: true
  show-actuator: true